MiPrimeraAPPAspNetCore/MiPrimeraAPPAspNetCore/Models/ErrorViewModel.cs
namespace MiPrimeraAPPAspNetCore.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MiPrimeraAPPAspNetCore/MiPrimeraAPPAspNetCore/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MiPrimeraAPPAspNetCore.Models;

namespace MiPrimeraAPPAspNetCore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MiPrimeraAPPAspNetCore/MiPrimeraAPPAspNetCore/Controllers/LaboratorioController.cs
using CapaDatos;
using CapaEntidad;
using CapaNegocio;
using Microsoft.AspNetCore.Mvc;

namespace MiPrimeraAPPAspNetCore.Controllers
{
    public class LaboratorioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public List<LaboratorioCLS> ListarLaboratorio()
        {
            LaboratorioBL obj = new LaboratorioBL();
            return obj.ListarLaboratorio();
        }

        public List<LaboratorioCLS> FiltrarLaboratorio(LaboratorioCLS objLaboratorio)
        {
            LaboratorioBL obj = new LaboratorioBL ();
            return obj.FiltrarLaboratorio(objLaboratorio);
        }

        public int GuardarLaboratorio(LaboratorioCLS objLaboratorio)
        {
            LaboratorioBL obj = new LaboratorioBL();
            return obj.GuardarLaboratorio(objLaboratorio);
        }

        public LaboratorioCLS RecuperarLaboratorio(int idLaboratorio)
        {
            LaboratorioBL obj = new LaboratorioBL();
            return obj.RecuperarLaboratorio(idLaboratorio);
        }

        public int EliminarLaboratorio(int idLaboratorio)
        {
            LaboratorioBL obj = new LaboratorioBL();
            return obj.EliminarLaboratorio(idLaboratorio);
        }

    }
}

MiPrimeraAPPAspNetCore/MiPrimeraAPPAspNetCore/Controllers/MedicamentoController.cs
using CapaNegocio;
using CapaEntidad;
using Microsoft.AspNetCore.Mvc;

namespace MiPrimeraAPPAspNetCore.Controllers
{
    public class MedicamentoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }


        public List<MedicamentoCLS> ListarMedicamento()
        {
            MedicamentoBL obj = new MedicamentoBL();
            return obj.ListarMedicamento();
        }

        public int GuardarMedicamento(MedicamentoCLS objMed)
        {
            MedicamentoBL obj = new MedicamentoBL();
            return obj.GuardarMedicamento(objMed);
        }

        public MedicamentoCLS RecuperarMedicamento(int idMedicamento)
        {
            MedicamentoBL obj = new MedicamentoBL();
            return obj.RecuperarMedicamento(idMedicamento);
        }

        public int EliminarMedicamento(int idMedicamento)
        {
            MedicamentoBL obj = new MedicamentoBL();
            return obj.EliminarMedicamento(idMedicamento);
        }

        }
}

MiPrimeraAPPAspNetCore/MiPrimeraAPPAspNetCore/Controllers/SucursalController.cs
using CapaNegocio;
using CapaEntidad;
using Microsoft.AspNetCore.Mvc;

namespace MiPrimeraAPPAspNetCore.Controllers
{
    public class SucursalController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public List<SucursalCLS> ListarSucursal()
        {
            SucursalBL obj = new SucursalBL();
            return obj.ListarSucursal();
        }


        public List<SucursalCLS> FiltrarSucursal(SucursalCLS objSucursal)
        {
            SucursalBL obj = new SucursalBL();
            return obj.FiltrarSucursal(objSucursal);
        }

        public int GuardarSucursal(SucursalCLS objSucursal)
        {
            SucursalBL obj = new SucursalBL();
            return obj.GuardarSucursal(objSucursal);
        }

        public SucursalCLS RecuperarSucursal(int idSucursal)
        {
            SucursalBL obj = new SucursalBL();
            return obj.RecuperarSucursal(idSucursal);
        }
        public int EliminarSucursal(int idSucursal)
        {
            SucursalBL obj = new SucursalBL();
            return obj.EliminarSucursal(idSucursal);
        }
    }
}

MiPrimeraAPPAspNetCore/MiPrimeraAPPAspNetCore/Controllers/TipoMedicamentoController.cs
using CapaNegocio;
using CapaEntidad;
using Microsoft.AspNetCore.Mvc;

namespace MiPrimeraAPPAspNetCore.Controllers
{
    public class TipoMedicamentoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public List<TipoMedicamentoCLS> ListarTipoMedicamento()
        {
            TipoMedicamentoBL tipoMedicamentoBL = new TipoMedicamentoBL();
            return tipoMedicamentoBL.ListartipoMedicamento();
        }

        public List<TipoMedicamentoCLS> FiltrartipoMedicamento(string nombre)
        {
            TipoMedicamentoBL tipoMedicamentoBL = new TipoMedicamentoBL();
            return tipoMedicamentoBL.FiltrartipoMedicamento(nombre);
        }

        public int GuardarTipoMedicamento(TipoMedicamentoCLS oTipoMedicamentoCLS)
        {
            TipoMedicamentoBL obj = new TipoMedicamentoBL();
            return obj.GuardarTipoMedicamento(oTipoMedicamentoCLS);
        }

        public TipoMedicamentoCLS RecuperarTipoMedicamento(int idTipoMedicamento)
        {
            TipoMedicamentoBL obj = new TipoMedicamentoBL();
            return obj.RecuperarTipoMedicamento(idTipoMedicamento);
        }

        public int EliminarTipoMedicamento(int idTipoMedicamento)
        {
            TipoMedicamentoBL obj = new TipoMedicamentoBL();
            return obj.EliminarTipoMedicamento(idTipoMedicamento);
        }
    }
}

MiPrimeraAPPAspNetCore/MiPrimeraAPPAspNetCore/Views/Medicamento/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1 class="display-6 text-primary text-center fw-bold"><i class="fa fa-pills"></i>  Medicamentos</h1>


<br />

<button type="button" class="btn btn-success" data-bs-toggle="modal" onclick="MostrarModal()">
    Nuevo Medicamento
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-earmark-plus-fill" viewBox="0 0 16 16">
        <path d="M9.293 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.707A1 1 0 0 0 13.707 4L10 .293A1 1 0 0 0 9.293 0M9.5 3.5v-2l3 3h-2a1 1 0 0 1-1-1M8.5 7v1.5H10a.5.5 0 0 1 0 1H8.5V11a.5.5 0 0 1-1 0V9.5H6a.5.5 0 0 1 0-1h1.5V7a.5.5 0 0 1 1 0" />
    </svg>
</button>

<br />


<!-- Modal -->
<div class="modal fade" id="modalMedicamento" tabindex="-1" aria-labelledby="modalMedicamentoLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalMedicamentoLabel">Agregar Medicamento</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="frmMedicamento" method="post" class="row g-3">
                    <div class="col-md-3">
                        <label for="inputIdLabModal" class="form-label">Id Medicamento</label>
                        <input type="text" class="form-control shadow-sm rounded" name="idMedicamento" id="idMedicamento" placeholder="Id Medicamento" readonly>
                    </div>
                    <div class="col-md-4">
                        <label for="inputCodigoModal" class="form-label">Codigo</label>
                        <input type="text" class="form-control shadow-sm rounded" name="codigo" id="codigo" placeholder="codigo">
                        <div class="invalid-feedback">Por favor, ingrese el código.</div>
                    </div>
                    <div class="col-md-5">
                        <label for="inputNombreModal" class="form-label">Nombre Medicamento</label>
                        <input type="text" class="form-control shadow-sm rounded" name="nombreMedicamento" id="nombreMedicamento" placeholder="Nombre">
                        <div class="invalid-feedback">Por favor, ingrese el nombre del medicamento.</div>
                    </div>
                    <div class="col-md-6">
                        <label for="cboTipoMedicamentoModal" class="form-label">Tipo Medicamento</label>
                        <select class="form-control shadow-sm rounded" name="idTipoMedicamento" id="tipoMedicamento">
                            <option value=''>Seleccione</option>
                            <!-- Opciones aquí -->
                        </select>
                        <div class="invalid-feedback">Por favor, seleccione el tipo de medicamento.</div>
                    </div>
                    <div class="col-md-6">
                        <label for="cboLaboratorioModal" class="form-label">Laboratorio</label>
                        <select class="form-control shadow-sm rounded" name="idLaboratorio" id="laboratorio">
                            <option value=''>Seleccione</option>
                            <!-- Opciones aquí -->
                        </select>
                        <div class="invalid-feedback">Por favor, seleccione el laboratorio.</div>
                    </div>
                    <div class="col-md-12">
                        <label for="inputUsoMedicamentoModal" class="form-label">Uso Medicamento</label>
                        <input type="text" class="form-control shadow-sm rounded" name="usoMedicamento" id="usoMedicamento" placeholder="Uso medicamento">
                        <div class="invalid-feedback">Por favor, ingrese el uso del medicamento.</div>
                    </div>
                    <div class="col-md-12">
                        <label for="inputContenidoModal" class="form-label">Contenido</label>
                        <input type="text" class="form-control shadow-sm rounded" name="contenido" id="contenido" placeholder="contenido">
                        <div class="invalid-feedback">Por favor, ingrese el contenido.</div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" onclick="GuardarMedicamento()">Guardar</button>
                <button type="button" class="btn btn-secondary" onclick="LimpiarMedicamento()">Limpiar</button>
            </div>
        </div>
    </div>
</div>

<br />

<div class="card shadow">
    <div class="card-header bg-info text-white">
        <h5 class="mb-0">Lista de medicamentos</h5>
    </div>
    <div class="card-body">
        <div id="divContenedorTabla"></div>
    </div>
</div>
<div id="divContenedorTabla"></div>



<script src="~/js/generic.js"></script>
<script src="~/js/medicamento.js"></script>

<script>
    document.getElementById('frmMedicamento').addEventListener('submit', function(event) {
        let form = event.target;
        let isValid = true;

        // Validar campos de texto
        let camposTexto = ['codigo', 'nombreMedicamento', 'usoMedicamento', 'contenido'];
        camposTexto.forEach(function(campo) {
            let input = form.querySelector('#' + campo);
            if (input.value.trim() === '') {
                input.classList.add('is-invalid');
                isValid = false;
            } else {
                input.classList.remove('is-invalid');
            }
        });

        // Validar selects
        let selects = ['tipoMedicamento', 'laboratorio'];
        selects.forEach(function(select) {
            let input = form.querySelector('#' + select);
            if (input.value === '') {
                input.classList.add('is-invalid');
                isValid = false;
            } else {
                input.classList.remove('is-invalid');
            }
        });

        if (!isValid) {
            event.preventDefault();
            event.stopPropagation();
        }
    });
</script>

MiPrimeraAPPAspNetCore/MiPrimeraAPPAspNetCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MiPrimeraAPPAspNetCore</title>
    <script type="importmap"></script>
    <link href="~/css/stylelayout.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MiPrimeraAPPAspNetCore.styles.css" asp-append-version="true" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet" />
	<link href="~/font-awesome/css/all.css" rel="stylesheet" />
	<link href="~/font-awesome/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.2.2/css/dataTables.dataTables.css" />
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/js/bootstrap.min.js" integrity="sha512-ykZ1QQr0Jy/4ZkvKuqWn4iF3lqPZyij9iRv6sGqLRdTPkY69YX6+7wvVGmsdBbiIfN/8OdsI7HABjvEok6ZopQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <style>
        body {
            display: flex;
            height: 100vh;
            margin: 0;
        }

        .side-nav {
            width: 200px;
            background-color: #3498db;
            padding-top: 40px;
            height: 100vh;
            position: fixed;
            left: 0;
            top: 0;
        }

        .nav-menu {
            list-style: none;
            padding: 0;
            margin: 0;
        }

        .nav-item {
            padding: 10px 20px;
        }

            .nav-item a {
                text-decoration: none;
                color: #fff;
                display: flex;
                align-items: center;
            }

            .nav-item.active {
                background-color: #fff;
                color: #2980b9;
            }

                .nav-item.active a {
                    color: #2980b9;
                }

        .menu-text {
            padding-left: 10px;
        }

        .main-content {
            margin-left: 220px;
            padding: 20px;
            width: calc(100% - 220px);
        }
    </style>
</head>

<body>  
    <header>
        @* <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3"> *@
        @*     <div class="container-fluid"> *@
        @*         <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MiPrimeraAPPAspNetCore</a> *@
        @*         <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" *@
        @*                 aria-expanded="false" aria-label="Toggle navigation"> *@
        @*             <span class="navbar-toggler-icon"></span> *@
        @*         </button> *@
        @*         <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between"> *@
        @*             <ul class="navbar-nav flex-grow-1"> *@
        @*                 <li class="nav-item"> *@
        @*                     <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a> *@
        @*                 </li> *@
        @*                 <li class="nav-item"> *@
        @*                     <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
        @*                 </li> *@
        @*                 <li class="nav-item"> *@
        @*                     <a class="nav-link text-dark" asp-area="" asp-controller="TipoMedicamento" asp-action="Index" >TipoMedicamento</a> *@
        @*                 </li> *@
        @*                 <li class="nav-item"> *@
        @*                     <a class="nav-link text-dark" asp-area="" asp-controller="Sucursal" asp-action="Index">Sucursal</a> *@
        @*                 </li> *@
        @*                 <li class="nav-item"> *@
        @*                     <a class="nav-link text-dark" asp-area="" asp-controller="Laboratorio" asp-action="Index">Laboratorio</a> *@
        @*                 </li> *@
        @*                 <li class="nav-item"> *@
        @*                     <a class="nav-link text-dark" asp-area="" asp-controller="Medicamento"  asp-action="Index">Medicamento</a> *@
        @*                 </li> *@
        @*             </ul> *@
        @*         </div> *@
        @*     </div> *@
        @* </nav> *@
    </header>
	<input type="hidden" id="hdfOculto" value="@Url.Content("~")" />

    <section id="sidebar">
        <div class="white-label">
        </div>
        <div id="sidebar-nav">
            <ul>
                <li><a href="/Home/Index"><i class="fa fa-home"></i> Home</a></li>
                <li><a href="/Home/Privacy"><i class="fa fa-lock"></i> Privacy</a></li>
                <li><a href="/TipoMedicamento/Index"><i class="fa fa-medkit"></i> Tipo Medicamento</a></li>
                <li><a href="/Sucursal/Index"><i class="fa fa-store"></i> Sucursal</a></li>
                <li><a href="/Laboratorio/Index"><i class="fa fa-flask"></i> Laboratorio</a></li>
                <li><a href="/Medicamento/Index"><i class="fa fa-pills"></i> Medicamento</a></li>
            </ul>
        </div>
    </section>

    <div class="main-content">


        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer>
            <div class="container">
                &copy; 2025 - Sistema Gestion Farmacia con .NET - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>


    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.datatables.net/2.2.2/js/dataTables.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MiPrimeraAPPAspNetCore/MiPrimeraAPPAspNetCore/Views/TipoMedicamento/Index.cshtml
@{
	ViewData["Title"] = "Index"; 
}


<h1 class="display-6 text-primary text-center fw-bold"> <i class="fa fa-medkit"></i>    Tipos de Medicamentos</h1>


<div class="input-group" style="max-width: 50%;">

        <span class="input-group-text bg-white rounded-start p-2">
            <i class="fas fa-search"></i>
        </span>

    <input id="txtNombreTipoMedicamento" onkeyup="FiltrarTipoMedicamento()" type="text" class="form-control form-control-sm shadow-sm rounded-end" placeholder="Ingresar tipo medicamento a buscar">
</div>

<br />


@* <fieldset id="fieldsetForm" class="border p-3 shadow rounded"> *@
@*     <legend class="h5">Gestionar Tipo Medicamento</legend> *@
@*      <div class="col-md-14"> *@
@*         <form id="frmTipoMedicamento" method="post" class="row g-2"> *@
@*             <div class="col-md-6"> *@
@*                 <label for="inputIdLab" class="form-label">Id Tipo Medicamento</label> *@
@*                 <input type="text" class="form-control shadow-sm rounded" name="idTipoMedicamento" id="idTipoMedicamento" placeholder="Id tipo Medicamento" readonly> *@
@*             </div> *@
@*             <div class="col-md-6"> *@
@*                 <label for="inputNombre" class="form-label">Nombre</label> *@
@*                 <input type="text" class="form-control shadow-sm rounded" name="nombre" id="nombre" placeholder="Nombre"> *@
@*             </div> *@
@*             <div class="col-md-12"> *@
@*                 <label for="inputDireccion" class="form-label">Descripcion</label> *@
@*                 <input type="text" class="form-control shadow-sm rounded" name="descripcion" id="descripcion" placeholder="Descripcion"> *@
@*             </div> *@
@*             <div class="col-12"> *@
@*                 <button type="button" class="btn btn-success" onclick="GuardarTipoMedicamento()">Guardar</button> *@
@*                 <button type="button" class="btn btn-secondary" onclick="LimpiarTipoMedicamento()">Limpiar</button> *@
@*             </div> *@
@*         </form> *@
@*     </div> *@
@* </fieldset> *@

<button type="button" class="btn btn-success" data-bs-toggle="modal" onclick="MostrarModal()">
    Nuevo Tipo Medicamento
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-earmark-plus-fill" viewBox="0 0 16 16">
        <path d="M9.293 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.707A1 1 0 0 0 13.707 4L10 .293A1 1 0 0 0 9.293 0M9.5 3.5v-2l3 3h-2a1 1 0 0 1-1-1M8.5 7v1.5H10a.5.5 0 0 1 0 1H8.5V11a.5.5 0 0 1-1 0V9.5H6a.5.5 0 0 1 0-1h1.5V7a.5.5 0 0 1 1 0" />
    </svg>
</button>

<br />
<br />  


<div class="card shadow">
    <div class="card-header bg-info text-white">
        <h5 class="mb-0">Lista de tipos de medicamentos</h5>
    </div>
    <div class="card-body">
        <div id="divContenedorTabla"></div>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="modalTipoMedicamento" tabindex="-1" aria-labelledby="modalTipoMedicamentoLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalTipoMedicamentoLabel">Gestionar Tipo Medicamento</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="frmTipoMedicamento" method="post" class="row g-3">
                    <div class="col-md-6">
                        <label for="inputIdTipoMedicamento" class="form-label">Id Tipo Medicamento</label>
                        <input type="text" class="form-control shadow-sm rounded" name="idTipoMedicamento" id="idTipoMedicamento" readonly>
                    </div>
                    <div class="col-md-6">
                        <label for="inputNombre" class="form-label">Nombre</label>
                        <input type="text" class="form-control shadow-sm rounded" name="nombre" id="nombre">
                    </div>
                    <div class="col-md-12">
                        <label for="inputDescripcion" class="form-label">Descripcion</label>
                        <input type="text" class="form-control shadow-sm rounded" name="descripcion" id="descripcion">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" onclick="GuardarTipoMedicamento()">Guardar</button>
                <button type="button" class="btn btn-secondary" onclick="LimpiarTipoMedicamento()">Limpiar</button>
            </div>
        </div>
    </div>
</div>

<script src="~/js/generic.js"></script>
<script src="~/js/tipomedicamento.js"></script>